#ifndef _APP_CFG_H
#define _APP_CFG_H

#define OS_TASK_TMR_PRIO  1

#define STARTUP_TASK_PRIO 2
#define STARTUP_TASK_STK_SIZE 64


#define SCAN_TASK_PRIO 9
#define SCAN_TASK_STK_SIZE 64


#define RS485_TX_TASK_PRIO 6
#define RS485_TX_TASK_STK_SIZE 256

#define RS485_RX_TASK_PRIO 7
#define RS485_RX_TASK_STK_SIZE 512



#endif
